version: 2

updates:
  - package-ecosystem: bun
    directories:
      - /
      - /packages/*
      - /samples/*
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore(actions)
